# permissions for end users to view iamusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iamuser-viewer-role
rules:
- apiGroups:
  - govind.dev
  resources:
  - iamusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - govind.dev
  resources:
  - iamusers/status
  verbs:
  - get
