---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - govind.dev
  resources:
  - iamusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - govind.dev
  resources:
  - iamusers/finalizers
  verbs:
  - update
- apiGroups:
  - govind.dev
  resources:
  - iamusers/status
  verbs:
  - get
  - patch
  - update
